# =========================
# GPIO MAP - MANTRAP SYSTEM
# =========================

# Outputs
BUZZER_PIN = 17

GREEN_LED_PIN = 5
RED_LED_PIN = 6

OUTER_SOLENOID_PIN = 18
INNER_SOLENOID_PIN = 19

# Inputs
OUTER_PUSH_BUTTON_PIN = 27
INNER_PUSH_BUTTON_PIN = 22
BACK_PUSH_BUTTON_PIN = 23

INNER_LIMIT_SWITCH_PIN = 24
OUTER_LIMIT_SWITCH_PIN = 16

# RFID RC522
RFID_RST_PIN = 25
RFID_SDA_PIN = 8

# UART Fingerprint
FINGERPRINT_RX_PIN = 15
FINGERPRINT_TX_PIN = 14
