# =========================
# SYSTEM STATES - MANTRAP
# =========================

SYSTEM_OFF = "SYSTEM_OFF"

IDLE_OUTER_OPEN = "IDLE_OUTER_OPEN"

WAIT_OUTER_DOOR_CLOSED = "WAIT_OUTER_DOOR_CLOSED"

AI_START_DELAY = "AI_START_DELAY"

PERSON_COUNTING = "PERSON_COUNTING"

MULTI_PERSON_WARNING = "MULTI_PERSON_WARNING"

AUTHENTICATION_READY = "AUTHENTICATION_READY"

AUTHENTICATION_PROCESSING = "AUTHENTICATION_PROCESSING"

WAIT_INNER_BUTTON_CONFIRM = "WAIT_INNER_BUTTON_CONFIRM"

INNER_DOOR_UNLOCKED = "INNER_DOOR_UNLOCKED"

ACCESS_GRANTED_FINISH = "ACCESS_GRANTED_FINISH"

CANCEL_AND_EXIT = "CANCEL_AND_EXIT"

SECURITY_LOCKDOWN = "SECURITY_LOCKDOWN"

ERROR_STATE = "ERROR_STATE"

MULTI_PERSON_EXIT_RELEASE = "MULTI_PERSON_EXIT_RELEASE"
